"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main-mac.py']
DATA_FILES = [
    ('assets', ['assets/helium.ico', 'assets/milesight.png', 'assets/images_rc.py'])
    ]
OPTIONS = {
	'iconfile':'assets/helium.ico',
	'packages':'PIL,PyQt5'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
