import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QColorDialog
import configparser
import webbrowser
from gui.minertools_gui_editminer_dialog import Ui_Dialog as Settingsdiag

def write_file():
    settingsini.write(open(settingsspath, 'w'))

settingsini = configparser.ConfigParser()
dir_path = '%s\\MinerTools\\' % os.environ['APPDATA'] 
settingsspath = '%ssettings.ini' % dir_path
global highdpi
global showlogo
global snapurl 
global snaplatesturl 
global constxtcolor 
global consbackcolor 

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 520)
        Dialog.setMinimumSize(QtCore.QSize(525, 520))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 800))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_settings = QtWidgets.QLabel(Dialog)
        self.label_settings.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings.setFont(font)
        self.label_settings.setStyleSheet("")
        self.label_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings.setObjectName("label_settings")
        self.horizontalLayout.addWidget(self.label_settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hzlayout_settings_general = QtWidgets.QHBoxLayout()
        self.hzlayout_settings_general.setSpacing(0)
        self.hzlayout_settings_general.setObjectName("hzlayout_settings_general")
        self.label_settings_general = QtWidgets.QLabel(Dialog)
        self.label_settings_general.setMinimumSize(QtCore.QSize(0, 12))
        self.label_settings_general.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_general.setFont(font)
        self.label_settings_general.setObjectName("label_settings_general")
        self.hzlayout_settings_general.addWidget(self.label_settings_general)
        self.button_help = QtWidgets.QPushButton(Dialog)
        self.button_help.setMaximumSize(QtCore.QSize(35, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_help.setFont(font)
        self.button_help.setObjectName("button_help")
        self.hzlayout_settings_general.addWidget(self.button_help)
        self.verticalLayout.addLayout(self.hzlayout_settings_general)
        self.hzlayout_highdpi = QtWidgets.QHBoxLayout()
        self.hzlayout_highdpi.setObjectName("hzlayout_highdpi")
        self.label_highdpi = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_highdpi.setFont(font)
        self.label_highdpi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_highdpi.setObjectName("label_highdpi")
        self.hzlayout_highdpi.addWidget(self.label_highdpi)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_highdpi.addItem(spacerItem)
        self.checkbox_highdpi = QtWidgets.QCheckBox(Dialog)
        self.checkbox_highdpi.setMinimumSize(QtCore.QSize(13, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkbox_highdpi.setFont(font)
        self.checkbox_highdpi.setText("")
        self.checkbox_highdpi.setObjectName("checkbox_highdpi")
        self.hzlayout_highdpi.addWidget(self.checkbox_highdpi)
        self.verticalLayout.addLayout(self.hzlayout_highdpi)
        self.hzlayout_logo = QtWidgets.QHBoxLayout()
        self.hzlayout_logo.setObjectName("hzlayout_logo")
        self.label_logo = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_logo.setFont(font)
        self.label_logo.setObjectName("label_logo")
        self.hzlayout_logo.addWidget(self.label_logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_logo.addItem(spacerItem1)
        self.checkbox_logo = QtWidgets.QCheckBox(Dialog)
        self.checkbox_logo.setText("")
        self.checkbox_logo.setObjectName("checkbox_logo")
        self.hzlayout_logo.addWidget(self.checkbox_logo)
        self.verticalLayout.addLayout(self.hzlayout_logo)
        self.hzlayout_snapurl = QtWidgets.QHBoxLayout()
        self.hzlayout_snapurl.setSpacing(8)
        self.hzlayout_snapurl.setObjectName("hzlayout_snapurl")
        self.label_snapurl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_snapurl.setFont(font)
        self.label_snapurl.setObjectName("label_snapurl")
        self.hzlayout_snapurl.addWidget(self.label_snapurl)
        self.lineedit_snapurl = QtWidgets.QLineEdit(Dialog)
        self.lineedit_snapurl.setObjectName("lineedit_snapurl")
        self.hzlayout_snapurl.addWidget(self.lineedit_snapurl)
        self.verticalLayout.addLayout(self.hzlayout_snapurl)
        self.hzlayout_snaplatest = QtWidgets.QHBoxLayout()
        self.hzlayout_snaplatest.setSpacing(8)
        self.hzlayout_snaplatest.setObjectName("hzlayout_snaplatest")
        self.label_snaplatesturl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_snaplatesturl.setFont(font)
        self.label_snaplatesturl.setObjectName("label_snaplatesturl")
        self.hzlayout_snaplatest.addWidget(self.label_snaplatesturl)
        self.lineedit_snaplatesturl = QtWidgets.QLineEdit(Dialog)
        self.lineedit_snaplatesturl.setObjectName("lineedit_snaplatesturl")
        self.hzlayout_snaplatest.addWidget(self.lineedit_snaplatesturl)
        self.verticalLayout.addLayout(self.hzlayout_snaplatest)
        self.hzlayout_settings_color = QtWidgets.QHBoxLayout()
        self.hzlayout_settings_color.setObjectName("hzlayout_settings_color")
        self.label_settings_color = QtWidgets.QLabel(Dialog)
        self.label_settings_color.setMinimumSize(QtCore.QSize(0, 12))
        self.label_settings_color.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_color.setFont(font)
        self.label_settings_color.setObjectName("label_settings_color")
        self.hzlayout_settings_color.addWidget(self.label_settings_color)
        self.verticalLayout.addLayout(self.hzlayout_settings_color)
        self.hzlayout_textcolor = QtWidgets.QHBoxLayout()
        self.hzlayout_textcolor.setSpacing(8)
        self.hzlayout_textcolor.setObjectName("hzlayout_textcolor")
        self.label_constxtcolor = QtWidgets.QLabel(Dialog)
        self.label_constxtcolor.setMaximumSize(QtCore.QSize(121, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_constxtcolor.setFont(font)
        self.label_constxtcolor.setObjectName("label_constxtcolor")
        self.hzlayout_textcolor.addWidget(self.label_constxtcolor)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_textcolor.addItem(spacerItem2)
        self.lineedit_txtcolor = QtWidgets.QLineEdit(Dialog)
        self.lineedit_txtcolor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_txtcolor.setObjectName("lineedit_txtcolor")
        self.hzlayout_textcolor.addWidget(self.lineedit_txtcolor)
        self.button_colorpickertxt = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_colorpickertxt.setFont(font)
        self.button_colorpickertxt.setObjectName("button_colorpickertxt")
        self.hzlayout_textcolor.addWidget(self.button_colorpickertxt)
        self.verticalLayout.addLayout(self.hzlayout_textcolor)
        self.hzlayout_consolecolor = QtWidgets.QHBoxLayout()
        self.hzlayout_consolecolor.setSpacing(8)
        self.hzlayout_consolecolor.setObjectName("hzlayout_consolecolor")
        self.label_consbackcolor = QtWidgets.QLabel(Dialog)
        self.label_consbackcolor.setMaximumSize(QtCore.QSize(154, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_consbackcolor.setFont(font)
        self.label_consbackcolor.setObjectName("label_consbackcolor")
        self.hzlayout_consolecolor.addWidget(self.label_consbackcolor)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_consolecolor.addItem(spacerItem3)
        self.lineedit_backcolor = QtWidgets.QLineEdit(Dialog)
        self.lineedit_backcolor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_backcolor.setObjectName("lineedit_backcolor")
        self.hzlayout_consolecolor.addWidget(self.lineedit_backcolor)
        self.button_colorpickerback = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_colorpickerback.setFont(font)
        self.button_colorpickerback.setObjectName("button_colorpickerback")
        self.hzlayout_consolecolor.addWidget(self.button_colorpickerback)
        self.verticalLayout.addLayout(self.hzlayout_consolecolor)
        self.hzlayout_settings_miner = QtWidgets.QHBoxLayout()
        self.hzlayout_settings_miner.setObjectName("hzlayout_settings_miner")
        self.label_settings_miner = QtWidgets.QLabel(Dialog)
        self.label_settings_miner.setMinimumSize(QtCore.QSize(0, 12))
        self.label_settings_miner.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_miner.setFont(font)
        self.label_settings_miner.setObjectName("label_settings_miner")
        self.hzlayout_settings_miner.addWidget(self.label_settings_miner)
        self.verticalLayout.addLayout(self.hzlayout_settings_miner)
        self.hzlayout_editminer = QtWidgets.QHBoxLayout()
        self.hzlayout_editminer.setObjectName("hzlayout_editminer")
        self.button_editminer = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_editminer.setFont(font)
        self.button_editminer.setObjectName("button_editminer")
        self.hzlayout_editminer.addWidget(self.button_editminer)
        self.verticalLayout.addLayout(self.hzlayout_editminer)
        self.hzlayout_settings_prog = QtWidgets.QHBoxLayout()
        self.hzlayout_settings_prog.setObjectName("hzlayout_settings_prog")
        self.label_settings_prog = QtWidgets.QLabel(Dialog)
        self.label_settings_prog.setMinimumSize(QtCore.QSize(0, 16))
        self.label_settings_prog.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_settings_prog.setFont(font)
        self.label_settings_prog.setObjectName("label_settings_prog")
        self.hzlayout_settings_prog.addWidget(self.label_settings_prog)
        self.verticalLayout.addLayout(self.hzlayout_settings_prog)
        self.hzlayout_prog1 = QtWidgets.QHBoxLayout()
        self.hzlayout_prog1.setSpacing(8)
        self.hzlayout_prog1.setObjectName("hzlayout_prog1")
        self.label_prog1_name = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog1_name.setFont(font)
        self.label_prog1_name.setObjectName("label_prog1_name")
        self.hzlayout_prog1.addWidget(self.label_prog1_name)
        self.lineedit_prog1_name = QtWidgets.QLineEdit(Dialog)
        self.lineedit_prog1_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog1_name.setFont(font)
        self.lineedit_prog1_name.setObjectName("lineedit_prog1_name")
        self.hzlayout_prog1.addWidget(self.lineedit_prog1_name)
        self.label_prog2_cmd_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog2_cmd_2.setFont(font)
        self.label_prog2_cmd_2.setObjectName("label_prog2_cmd_2")
        self.hzlayout_prog1.addWidget(self.label_prog2_cmd_2)
        self.lineedit_prog1_cmd = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog1_cmd.setFont(font)
        self.lineedit_prog1_cmd.setObjectName("lineedit_prog1_cmd")
        self.hzlayout_prog1.addWidget(self.lineedit_prog1_cmd)
        self.verticalLayout.addLayout(self.hzlayout_prog1)
        self.hzlayout_prog2 = QtWidgets.QHBoxLayout()
        self.hzlayout_prog2.setSpacing(8)
        self.hzlayout_prog2.setObjectName("hzlayout_prog2")
        self.label_prog2_name = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog2_name.setFont(font)
        self.label_prog2_name.setObjectName("label_prog2_name")
        self.hzlayout_prog2.addWidget(self.label_prog2_name)
        self.lineedit_prog2_name = QtWidgets.QLineEdit(Dialog)
        self.lineedit_prog2_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog2_name.setFont(font)
        self.lineedit_prog2_name.setObjectName("lineedit_prog2_name")
        self.hzlayout_prog2.addWidget(self.lineedit_prog2_name)
        self.label_prog2_cmd = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog2_cmd.setFont(font)
        self.label_prog2_cmd.setObjectName("label_prog2_cmd")
        self.hzlayout_prog2.addWidget(self.label_prog2_cmd)
        self.lineedit_prog2_cmd = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog2_cmd.setFont(font)
        self.lineedit_prog2_cmd.setObjectName("lineedit_prog2_cmd")
        self.hzlayout_prog2.addWidget(self.lineedit_prog2_cmd)
        self.verticalLayout.addLayout(self.hzlayout_prog2)
        self.hzlayout_prog3 = QtWidgets.QHBoxLayout()
        self.hzlayout_prog3.setSpacing(8)
        self.hzlayout_prog3.setObjectName("hzlayout_prog3")
        self.label_prog3_name = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog3_name.setFont(font)
        self.label_prog3_name.setObjectName("label_prog3_name")
        self.hzlayout_prog3.addWidget(self.label_prog3_name)
        self.lineedit_prog3_name = QtWidgets.QLineEdit(Dialog)
        self.lineedit_prog3_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog3_name.setFont(font)
        self.lineedit_prog3_name.setObjectName("lineedit_prog3_name")
        self.hzlayout_prog3.addWidget(self.lineedit_prog3_name)
        self.label_prog3_cmd = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_prog3_cmd.setFont(font)
        self.label_prog3_cmd.setObjectName("label_prog3_cmd")
        self.hzlayout_prog3.addWidget(self.label_prog3_cmd)
        self.lineedit_prog3_cmd = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_prog3_cmd.setFont(font)
        self.lineedit_prog3_cmd.setObjectName("lineedit_prog3_cmd")
        self.hzlayout_prog3.addWidget(self.lineedit_prog3_cmd)
        self.verticalLayout.addLayout(self.hzlayout_prog3)
        self.hzlayout_settings_tweak = QtWidgets.QHBoxLayout()
        self.hzlayout_settings_tweak.setObjectName("hzlayout_settings_tweak")
        self.label_tweaksettings = QtWidgets.QLabel(Dialog)
        self.label_tweaksettings.setMinimumSize(QtCore.QSize(0, 16))
        self.label_tweaksettings.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_tweaksettings.setFont(font)
        self.label_tweaksettings.setObjectName("label_tweaksettings")
        self.hzlayout_settings_tweak.addWidget(self.label_tweaksettings)
        self.verticalLayout.addLayout(self.hzlayout_settings_tweak)
        self.hzlayout_pui = QtWidgets.QHBoxLayout()
        self.hzlayout_pui.setObjectName("hzlayout_pui")
        self.label_pui = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_pui.setFont(font)
        self.label_pui.setObjectName("label_pui")
        self.hzlayout_pui.addWidget(self.label_pui)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hzlayout_pui.addWidget(self.line)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_pui.addItem(spacerItem4)
        self.spinbox_pui = QtWidgets.QSpinBox(Dialog)
        self.spinbox_pui.setMinimumSize(QtCore.QSize(90, 0))
        self.spinbox_pui.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinbox_pui.setFont(font)
        self.spinbox_pui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_pui.setMaximum(10000000)
        self.spinbox_pui.setProperty("value", 600000)
        self.spinbox_pui.setObjectName("spinbox_pui")
        self.hzlayout_pui.addWidget(self.spinbox_pui)
        self.verticalLayout.addLayout(self.hzlayout_pui)
        self.hzlayout_mic = QtWidgets.QHBoxLayout()
        self.hzlayout_mic.setObjectName("hzlayout_mic")
        self.label_mic = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mic.setFont(font)
        self.label_mic.setObjectName("label_mic")
        self.hzlayout_mic.addWidget(self.label_mic)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_mic.addItem(spacerItem5)
        self.spinbox_mic = QtWidgets.QSpinBox(Dialog)
        self.spinbox_mic.setMinimumSize(QtCore.QSize(90, 0))
        self.spinbox_mic.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinbox_mic.setFont(font)
        self.spinbox_mic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_mic.setMaximum(1000)
        self.spinbox_mic.setProperty("value", 60)
        self.spinbox_mic.setObjectName("spinbox_mic")
        self.hzlayout_mic.addWidget(self.spinbox_mic)
        self.verticalLayout.addLayout(self.hzlayout_mic)
        self.hzlayout_ogc = QtWidgets.QHBoxLayout()
        self.hzlayout_ogc.setObjectName("hzlayout_ogc")
        self.label_ogc = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ogc.setFont(font)
        self.label_ogc.setObjectName("label_ogc")
        self.hzlayout_ogc.addWidget(self.label_ogc)
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_ogc.addItem(spacerItem6)
        self.spinbox_ogc = QtWidgets.QSpinBox(Dialog)
        self.spinbox_ogc.setMinimumSize(QtCore.QSize(90, 0))
        self.spinbox_ogc.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinbox_ogc.setFont(font)
        self.spinbox_ogc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_ogc.setMaximum(200)
        self.spinbox_ogc.setProperty("value", 20)
        self.spinbox_ogc.setObjectName("spinbox_ogc")
        self.hzlayout_ogc.addWidget(self.spinbox_ogc)
        self.verticalLayout.addLayout(self.hzlayout_ogc)
        self.hzlayout_ncm = QtWidgets.QHBoxLayout()
        self.hzlayout_ncm.setObjectName("hzlayout_ncm")
        self.label_ncm = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ncm.setFont(font)
        self.label_ncm.setObjectName("label_ncm")
        self.hzlayout_ncm.addWidget(self.label_ncm)
        spacerItem7 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_ncm.addItem(spacerItem7)
        self.spinbox_ncm = QtWidgets.QSpinBox(Dialog)
        self.spinbox_ncm.setMinimumSize(QtCore.QSize(90, 0))
        self.spinbox_ncm.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinbox_ncm.setFont(font)
        self.spinbox_ncm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_ncm.setMaximum(200)
        self.spinbox_ncm.setProperty("value", 16)
        self.spinbox_ncm.setObjectName("spinbox_ncm")
        self.hzlayout_ncm.addWidget(self.spinbox_ncm)
        self.verticalLayout.addLayout(self.hzlayout_ncm)
        self.hzlayout_savecancel = QtWidgets.QHBoxLayout()
        self.hzlayout_savecancel.setObjectName("hzlayout_savecancel")
        self.button_save = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_save.setFont(font)
        self.button_save.setObjectName("button_save")
        self.hzlayout_savecancel.addWidget(self.button_save)
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hzlayout_savecancel.addItem(spacerItem8)
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_cancel.setFont(font)
        self.button_cancel.setObjectName("button_cancel")
        self.hzlayout_savecancel.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.hzlayout_savecancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Miner Tools Settings"))
        self.label_settings.setText(_translate("Dialog", "Miner Tools Settings"))
        self.label_settings_general.setText(_translate("Dialog", "General Settings:"))
        self.button_help.setText(_translate("Dialog", "Help"))
        self.label_highdpi.setText(_translate("Dialog", "Start with High DPI Scaling:"))
        self.label_logo.setText(_translate("Dialog", "Display Logo in Console:"))
        self.label_snapurl.setText(_translate("Dialog", "Snap Url:"))
        self.label_snaplatesturl.setText(_translate("Dialog", "Sap Url Latest:"))
        self.label_settings_color.setText(_translate("Dialog", "Console Color Settings:"))
        self.label_constxtcolor.setText(_translate("Dialog", "Console Text Color:"))
        self.button_colorpickertxt.setText(_translate("Dialog", "Color Picker"))
        self.label_consbackcolor.setText(_translate("Dialog", "Console Background Color:"))
        self.button_colorpickerback.setText(_translate("Dialog", "Color Picker"))
        self.label_settings_miner.setText(_translate("Dialog", "Configure your Miners:"))
        self.button_editminer.setText(_translate("Dialog", "Edit Miner List"))
        self.label_settings_prog.setText(_translate("Dialog", "Programmable Buttons:"))
        self.label_prog1_name.setText(_translate("Dialog", "Name:"))
        self.lineedit_prog1_name.setText(_translate("Dialog", "Programmable1"))
        self.label_prog2_cmd_2.setText(_translate("Dialog", "Command:"))
        self.lineedit_prog1_cmd.setText(_translate("Dialog", "uptime"))
        self.label_prog2_name.setText(_translate("Dialog", "Name:"))
        self.lineedit_prog2_name.setText(_translate("Dialog", "Programmable2"))
        self.label_prog2_cmd.setText(_translate("Dialog", "Command:"))
        self.lineedit_prog2_cmd.setText(_translate("Dialog", "uptime"))
        self.label_prog3_name.setText(_translate("Dialog", "Name:"))
        self.lineedit_prog3_name.setText(_translate("Dialog", "Programmable3"))
        self.label_prog3_cmd.setText(_translate("Dialog", "Command:"))
        self.lineedit_prog3_cmd.setText(_translate("Dialog", "uptime"))
        self.label_tweaksettings.setText(_translate("Dialog", "Tweak Peer Book Settings:"))
        self.label_pui.setText(_translate("Dialog", "Peerbook Update Interval:"))
        self.label_mic.setText(_translate("Dialog", "Max Inbound Connections:"))
        self.label_ogc.setText(_translate("Dialog", "Outbound Gossip Connections:"))
        self.label_ncm.setText(_translate("Dialog", "Num Consensus Members:"))
        self.button_save.setText(_translate("Dialog", "Save Changes"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))


# Define Button Actions
        self.button_colorpickertxt.clicked.connect(self.opentxtcolorColorDialog)
        self.button_colorpickerback.clicked.connect(self.openbackcolorColorDialog)
        self.button_cancel.clicked.connect(Dialog.reject)
        self.button_save.clicked.connect(self.saveconfig)
        self.readconfig()
        self.button_editminer.clicked.connect(self.open_editminer)
        self.lineedit_backcolor.setReadOnly(True)
        self.lineedit_txtcolor.setReadOnly(True)
        self.button_help.clicked.connect(self.open_help)

# Define Functions
    def open_help(self):
        webbrowser.open("https://minertools.doit.net", new=0, autoraise=True)

    def readconfig(self):
        settingsini.read(settingsspath)
        try:
            highdpi = settingsini.get('systemsettings', 'highdpi')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'highdpi', '1')
            highdpi = "1"
            write_file()
        try:
            showlogo = settingsini.get('systemsettings', 'showlogo')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'showlogo', '0')
            write_file()
        try:
            snapurl = settingsini.get('systemsettings', 'snapurl')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'snapurl', 'http://snapshots-wtf.sensecapmx.cloud/snap-')
            write_file()
        try:
            snaplatesturl = settingsini.get('systemsettings', 'snaplatesturl')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'snaplatesturl', 'http://snapshots-wtf.sensecapmx.cloud/latest-snap.json')
            write_file()
        try:
            constxtcolor = settingsini.get('systemsettings', 'constxtcolor')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'constxtcolor', '#A4E87F')
            write_file()
        try:
            consbackcolor = settingsini.get('systemsettings', 'consbackcolor')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'consbackcolor', '#212121')
            write_file()

        try:
            pui_value = settingsini.get('systemsettings', 'pui_value')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'pui_value', '600000')
            write_file()
        try:
            mic_value = settingsini.get('systemsettings', 'mic_value')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'mic_value', '60')
            write_file()
        try:
            ogc_value = settingsini.get('systemsettings', 'ogc_value')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'ogc_value', '20')
            write_file()
        try:
            ncm_value = settingsini.get('systemsettings', 'ncm_value')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'ncm_value', '16')
            write_file()
        try:
            progbut1_name = settingsini.get('systemsettings', 'progbut1_name')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut1_name', 'Programmable1')
            write_file()
        try:
            progbut2_name = settingsini.get('systemsettings', 'progbut2_name')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut2_name', 'Programmable2')
            write_file()
        try:
            progbut3_name = settingsini.get('systemsettings', 'progbut3_name')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut3_name', 'Programmable3')
            write_file()
        try:
            progbut1_cmd = settingsini.get('systemsettings', 'progbut1_cmd')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut1_cmd', 'uptime')
            write_file()
        try:
            progbut2_cmd = settingsini.get('systemsettings', 'progbut2_cmd')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut2_cmd', 'uptime')
            write_file()
        try:
            progbut3_cmd = settingsini.get('systemsettings', 'progbut3_cmd')
        except configparser.NoOptionError:
            settingsini.set('systemsettings', 'progbut3_cmd', 'uptime')
            write_file()
        

        if highdpi == "1":
            self.checkbox_highdpi.setChecked(True)
        else:
            self.checkbox_highdpi.setChecked(False)
        if showlogo == "1":
            self.checkbox_logo.setChecked(True)
        else:
            self.checkbox_logo.setChecked(False)
        self.lineedit_snapurl.setText(snapurl)
        self.lineedit_snaplatesturl.setText(snaplatesturl)
        self.lineedit_txtcolor.setText(constxtcolor)
        self.lineedit_txtcolor.setStyleSheet("background-color:%s;" % constxtcolor)
        self.lineedit_backcolor.setText(consbackcolor)
        self.lineedit_backcolor.setStyleSheet("background-color:%s;" % consbackcolor)
        self.spinbox_mic.setValue(int(mic_value))
        self.spinbox_ogc.setValue(int(ogc_value))
        self.spinbox_pui.setValue(int(pui_value))
        self.spinbox_ncm.setValue(int(ncm_value))
        self.lineedit_prog1_name.setText(progbut1_name)
        self.lineedit_prog2_name.setText(progbut2_name)
        self.lineedit_prog3_name.setText(progbut3_name)
        self.lineedit_prog1_cmd.setText(progbut1_cmd)
        self.lineedit_prog2_cmd.setText(progbut2_cmd)
        self.lineedit_prog3_cmd.setText(progbut3_cmd)

    def saveconfig(self):
        settingsini.read(settingsspath)
        if self.checkbox_highdpi.checkState() == 2:
            highdpistatus = 1
        else:
            highdpistatus = 0
        if self.checkbox_logo.checkState() == 2:
            showlogostatus = 1
        else:
            showlogostatus = 0
        settingsini.set('systemsettings', 'highdpi', '%s' % highdpistatus)
        settingsini.set('systemsettings', 'snapurl', '%s' % self.lineedit_snapurl.text())
        settingsini.set('systemsettings', 'snaplatesturl', '%s' % self.lineedit_snaplatesturl.text())
        settingsini.set('systemsettings', 'constxtcolor', '%s' % self.lineedit_txtcolor.text())
        settingsini.set('systemsettings', 'consbackcolor', '%s' % self.lineedit_backcolor.text())
        settingsini.set('systemsettings','showlogo', '%s' % showlogostatus)

        settingsini.set('systemsettings','pui_value', '%s' % self.spinbox_pui.value())
        settingsini.set('systemsettings','mic_value', '%s' % self.spinbox_mic.value())
        settingsini.set('systemsettings','ogc_value', '%s' % self.spinbox_ogc.value())
        settingsini.set('systemsettings','ncm_value', '%s' % self.spinbox_ncm.value())
        settingsini.set('systemsettings','progbut1_name', '%s' % self.lineedit_prog1_name.text())
        settingsini.set('systemsettings','progbut2_name', '%s' % self.lineedit_prog2_name.text())
        settingsini.set('systemsettings','progbut3_name', '%s' % self.lineedit_prog3_name.text())
        settingsini.set('systemsettings','progbut1_cmd', '%s' % self.lineedit_prog1_cmd.text())
        settingsini.set('systemsettings','progbut2_cmd', '%s' % self.lineedit_prog2_cmd.text())
        settingsini.set('systemsettings','progbut3_cmd', '%s' % self.lineedit_prog3_cmd.text())
        write_file()
        self.button_cancel.click()

    def openbackcolorColorDialog(self):
        color = QColorDialog.getColor()
        self.lineedit_backcolor.setText(color.name())
        self.lineedit_backcolor.setStyleSheet("background-color:%s;" % (color.name()))

    def opentxtcolorColorDialog(self):
        color = QColorDialog.getColor()
        self.lineedit_txtcolor.setText(color.name())
        self.lineedit_txtcolor.setStyleSheet("background-color:%s;" % (color.name()))

    def open_editminer(self):
        editminerset = QtWidgets.QDialog()
        editminerset.ui = Settingsdiag()
        editminerset.ui.setupUi(editminerset)
        editminerset.setWindowFlags(QtCore.Qt.WindowType.CustomizeWindowHint)
        editminerset.setWindowFlags(editminerset.windowFlags() & ~QtCore.Qt.WindowType.WindowMinimizeButtonHint & QtCore.Qt.WindowType.WindowCloseButtonHint)
        editminerset.setWindowIcon(QtGui.QIcon('assets/helium.ico'))
        editminerset.exec_()
        editminerset.show()
        self.readconfig()